### ISSUE TITLE
I had to yank 0.3

### ISSUE THREAD

**Issue by m4b** [capstone-rust/capstone-sys#2]
This is primarily my fault for not doing an in depth review, and not wanting to maintain this very much, but imho, the crate is:

1. a substantial downgrade from the previous version, 0.2
2. has multiple bugs

For example, here are some major issues after trying to use it briefly:

1. Using system binding balloons a fresh compile to 1-3 minutes - this is _completely_ unacceptable for essentially the rust version of a simple C `#include`. For comparison, compiling a fresh capstone on fcc8eac using system bindings was 1/2-2 _seconds_...
2. None of the bindings are documented anymore!
3. Related to 1, using the bundled bindings should never ever pull down bindgen, etc., and unrelated crates
4. There's no reason to use `lazy_static` in the `build.rs` for a log file (the build isn't multithreaded); all this does is complicate the build and increase compile times.  Furthermore, there's no reason to have a build log file at all, as this is all printed directly in the output file in the respective deps directory. Even worse, passing `-vvv` doesn't print anything anymore; this just breaks user expectations.
5. The feature flags aren't coherent - the `lib.rs` includes either the bundled or not-bundled depending on the feature flag, but `use_system_capstone` isn't reflected in this at all, nor is it depended on or dependent of the bundled flag
6. There are non-existent feature flags in the `build.rs`, `"build_src_cmake"` (from the previous iterations); this indicates to me it was never tested.
7. Bindgen dynamic output needs to be an optional feature flag; this should 100% not be the default

Those are some of the major, show-stopping issues that forced me to yank.

Besides this, I'm thinking that bundling capstone was a really bad move; this is old style C vendoring. There was nothing wrong with the git module before, it was easily updateable, and it didn't force _even a system binding user_ to download a 30MB crate.

Furthermore, the argument that the user doesn't have an internet connection is:

1. ok, then they should get their sys-admin or themselves to compile and install `libcapstone.so` and use the system bindings, or
2. untenable; they just used cargo to either download this crate as a dep, or they got it from the internet somewhere.  Furthermore, the 4 dependencies and their 20 transitive dependencies need to be downloaded and compiled, so this is still untenable.

I understand that git submodules are _sometimes_ undesirable, but I think this is a specific usecase where they are perfect precisely for what they're intended; and we don't force a 30MB download to someone who wants a 30k rust header file equivalent.

This brings me to the second point: using bindgen.  I'm not even convinced this is a motivating usecase for the capstone bindings.  As far as I know, the capstone ABI has been pretty rock-solid; I can't remember the last time it was changed, and I suspect it won't change anytime soon.  Using bindgen to generate bindings _only_ makes sense for the architecture header files which would have been prohitively difficult to write by hand; but could have been bindgen'd and then checked in quite easily, and the problem would have been solved.

Again, I should have downloaded, analyzed, and "lived in" the new version for a bit before merging and transferring this crate, but here we are.

Please don't take this in the wrong way; the current situation is just as much my fault as anyones, not having performed due process before the merge - but I hope we can rectify the situation, because as it stands now, I simply can't release these bindings as they stand.

At the end of the day, my decision to yank essentially came down to my answer to these questions:

1. Would I be ok using this library and reading the documentation? - No
2. Would I fork or write my own because it doesn't let me do what I want? - Yes

```
0.2 fresh compile, compiles capstone from source, after downloading from internet:
    Finished dev [unoptimized + debuginfo] target(s) in 14.13 secs

0.3 fresh compile, compiles bundled capstone from source
    Finished dev [unoptimized + debuginfo] target(s) in 140.72 secs
```

**Comment by tmfink** [comment]
Thanks for the feedback @m4b; I don't want to make decisions in isolation.
I think you make valid points--I'll see if I can make some improvements.

**Comment by m4b** [comment]
To be clear the work you did is useful but I think we can do better. 

Also for the time being let's not worry about submodules; can always re-add it later, etc. first priority is to get the build.rs working properly with feature flags and making the system bindings have only pkg-config as a dep
