### ISSUE TITLE
Moving to Capstone 4.0?

### ISSUE THREAD

**Issue by waywardmonkeys** [capstone-rust/capstone-sys#29]
There's going to be a new 4.0 release of Capstone soon-ish and there are already release candidates being made for it. This adds a bunch of new architectures and some new features.

Is there interest in moving this crate to one of the release candidates or should we wait for the official 4.0 release?

Upstream, I've started converting their doc comments to the format that `bindgen` picks up, so that the `bindgen` stuff can draw more directly from the official Capstone doc comments if that's useful.  Unfortunately, this turns up that there are at least 2 bugs in how `bindgen` processes doc comments that I plan to fix.

**Comment by tmfink** [comment]
There's is definitely interest, I just did not want to:
- Move this crate to a new version when the API might change
- Concurrently maintain a master and next branches

Thanks for your help.

**Comment by tmfink** [comment]
Another thing I have thought about is getting an API into Capstone that allows the user to completely manage their own memory. If there is not sufficient memory allocated, then calls should fail.

This would allow us to do all allocations from Rust.

Currently, when you do `cs_open()`, the "init" functions for each architecture call `cs_mem_alloc()`. Even when you use `cs_disasm_iter()`, you *must* pre-allocate with the `cs_malloc()`, which will call `cs_mem_alloc()` twice when detail is enabled.

I want to be able stack allocate a Capstone object from Rust code. If I allocate from Rust, then I can more safely/easily free the memory.

**Comment by tmfink** [comment]
@ZhangZhuoSJTU thanks for your enthusiasm in trying update the bundled Capstone library!

In order to make the build work, I suggest that you examine at the [Makefile](https://github.com/capstone-rust/capstone-sys/blob/master/capstone/Makefile) and [CMakeLists.txt](https://github.com/capstone-rust/capstone-sys/blob/master/capstone/CMakeLists.txt) and build logs.

**Comment by waywardmonkeys** [comment]
Hello!

Those build warnings should get fixed upstream...

You should be able to use the `master` branch now since that will be what becomes the 4.0 release.

I got the doc comment upstream changed to be doxygen style so that bindgen should be able to pick up the comments now. It will have a few issues that we will have to post-process for now until we can fix bindgen.
