### ISSUE TITLE
Automate documentation

### ISSUE THREAD

**Issue by tmfink** [capstone-rust/capstone-sys#6]
Bindgen no longer generates documentation for elements. However, Rust doc comments are more friendly than reading the C `capstone` headers.

We should add a script (or Rust code) that can add documentation to the pre-generated bindings.

**Comment by tmfink** [comment]
This is based on discussion from pull-request #3.

**Comment by m4b** [comment]
Can you just cherry pick the doc commit for now for the release ? And then add more robust solution later. 

I say this cause I think need to release in a day or two because I'm leaving for a bit and won't be able to release for a bit, so somewhat in a rush :)

**Comment by tmfink** [comment]
Handled with [scripts/add_doc_comments.py](https://github.com/capstone-rust/capstone-sys/blob/master/scripts/add_doc_comments.py)
