### ISSUE TITLE
Support Windows

### ISSUE THREAD

**Issue by tmfink** [capstone-rust/capstone-sys#7]
Windows support is untested/unsupported. We should fix that.

We can use App Veyor for Windows CI:
https://www.appveyor.com/

**Comment by Shaddy** [comment]
Are there plans to merge the windows support with 0.6.0?

**Comment by tmfink** [comment]
@Shaddy I worked on this issue a little but ran into bugs. Some of the auto-generated bindgen unit tests failed on Windows.

My current plan is to update the version of bindgen used first, then come back to this issue. Maybe upgrading bindgen will fix some of the bugs. I do not expect this to be fixed in the 0.6.0 release.

If you would like, I could assign this issue to you (no worries either way).

**Comment by Shaddy** [comment]
I've been testing the 0.5.0 which appearently uses cmake (make.sh), didnt ran all the tests so I would give a try on this. Antoher thing is that for me has more sense to use "msbuild" for building instead, which capstone supports under Windows but it will probably require more changes and tests. Not familiar with bindgen, ill give a try.

**Comment by tmfink** [comment]
Implemented with PR #17
